#!/usr/bin/env bash
#This script shows the content of the current directory in a list format, displaying only the part of the name after the first dash.
for f in *; do
	echo "$f" | cut -d "-" -f2;
done
