#!/usr/bin/env bash
#This script display the list of currently running processes
ps -faux | less
#-a 
#-u le pido la informacion detallada
#-x agrega los procesos que no tienen control de terminal
#-f le ordena por jerarquia
