#!/usr/bin/env bash
#This script creat a file containing its PID, displays To infinity and beyond indefinetly, displays I hate the kill command when receiving SIGTERM signal, displays Y U no love me) when receiving SIGINY signal and deletes the files /var/run/myscript.pid and therminates itself when receiving a SIGQUIT or SIGTERM signal
touch /var/run/myscript.pid
pid_script=$(pgrep -f  myscript.pid)
echo "$pid_script" >> /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'" SIGTERM
	trap "echo 'Y U no love me'" SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM
done

