#!/usr/bin/env bash
#This script manage daemons and uses init scripts, using the common instructions start, restart and stop


#Defino funcion start y stop, en este caso restart seria la combinacion de las dos anteriores
start() {
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" >> /var/run/my_process.pid #$! guarda el pid del script ejecutado con un & 
}

stop() {
	kill -9 $!
	rm /var/run/my_process.pid
}

case "$1" in
	start)
		start
		echo "manage_my_process started"
		;;
	stop)
		echo "manage_my_process stopped"
		stop
		;;
	restart)
		echo "manage_my_process restarted"
		stop
		start
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0	
